"""init

Revision ID: f33d43641691
Revises: 
Create Date: 2022-07-14 11:08:42.135321

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f33d43641691"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("admin_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("admin_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("admin_email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("admin_password", sa.VARCHAR(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("admin_id"),
        sa.UniqueConstraint("admin_email"),
    )
    op.create_index(op.f("ix_admins_admin_id"), "admins", ["admin_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("project_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_title", sa.VARCHAR(length=100), nullable=False),
        sa.Column("project_manager", sa.VARCHAR(length=100), nullable=False),
        sa.Column("project_description", sa.VARCHAR(length=500), nullable=True),
        sa.Column("project_manager_email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("project_id"),
        sa.UniqueConstraint("project_title"),
    )
    op.create_index(
        op.f("ix_projects_project_id"), "projects", ["project_id"], unique=False
    )
    op.create_table(
        "file_type",
        sa.Column("file_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_type", sa.VARCHAR(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("file_type_id"),
    )
    op.create_index(
        op.f("ix_file_type_file_type_id"), "file_type", ["file_type_id"], unique=False
    )
    op.create_table(
        "project_access_tokens",
        sa.Column("access_token_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("access_token", sa.VARCHAR(length=100), nullable=True),
        sa.Column("is_write", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("expired", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("access_token_id"),
        sa.UniqueConstraint("access_token"),
    )
    op.create_index(
        op.f("ix_project_access_tokens_access_token_id"),
        "project_access_tokens",
        ["access_token_id"],
        unique=False,
    )
    op.create_table(
        "file",
        sa.Column("file_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("file_type_id", sa.Integer(), nullable=True),
        sa.Column("is_view", sa.Boolean(), nullable=True),
        sa.Column("file_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("origin_file_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("version", sa.VARCHAR(length=20), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_type_id"],
            ["file_type.file_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_index(op.f("ix_file_file_id"), "file", ["file_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_file_id"), table_name="file")
    op.drop_table("file")
    op.drop_index(
        op.f("ix_project_access_tokens_access_token_id"),
        table_name="project_access_tokens",
    )
    op.drop_table("project_access_tokens")
    op.drop_index(op.f("ix_file_type_file_type_id"), table_name="file_type")
    op.drop_table("file_type")
    op.drop_index(op.f("ix_projects_project_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_admins_admin_id"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
